config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :abouts
  resources :stores
  resources :payrolls
  resources :employees
  resources :administrators, except: [:destroy]
  resources :payments, only: %i[new create]

  devise_for :users

  devise_scope :user do
    get 'users/table', to: 'users/registrations#table', as: 'user_table'
  end

  resources :products do
    post 'comprar', on: :member
    collection do
      get 'search'
      get 'table'
    end
  end

  resources :purchases do
    patch 'close', on: :member
    collection do
      get 'user_last_purchase'
    end
  end

  resources :departments do
    collection do
      get 'table'
    end
  end

  resources :categories do
    collection do
      get 'table'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  delete '/item_purchases/:id', to: 'item_purchases#destroy', as: 'item_purchase'

  resources :item_purchases do
    member do
      post 'growth'
      post 'reduction'
    end
  end

  root 'products#index'
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  belongs_to :administrator
  has_one_attached :logo

  validates :payroll_day, presence: true,
                          numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 28 }
  validates :facebook,
            format: { with: %r{\Ahttps://www\.facebook\.com/}, message: 'deve começar com https://www.facebook.com/' }, allow_blank: true
  validates :instagram,
            format: { with: %r{\Ahttps://www\.instagram\.com/}, message: 'deve começar com https://www.instagram.com/' }, allow_blank: true
  validates :twitter, format: { with: %r{\Ahttps://twitter\.com/}, message: 'deve começar com https://twitter.com/' },
                      allow_blank: true
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  before_action :set_store, only: %i[show edit update destroy]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show; end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit; end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:kind, :theme, :payroll_day, :administrator_id, :facebook, :instagram, :twitter)
  end
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.number_field :kind %>
  </div>

  <div>
    <%= form.label :theme, style: "display: block" %>
    <%= form.number_field :theme %>
  </div>

  <div>
    <%= form.label :payroll_day, style: "display: block" %>
    <%= form.number_field :payroll_day %>
  </div>

  <div>
    <%= form.label :administrator_id, style: "display: block" %>
    <%= form.text_field :administrator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Kind:</strong>
    <%= store.kind %>
  </p>

  <p>
    <strong>Theme:</strong>
    <%= store.theme %>
  </p>

  <p>
    <strong>Payroll day:</strong>
    <%= store.payroll_day %>
  </p>

  <p>
    <strong>Administrator:</strong>
    <%= store.administrator_id %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>