config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :abouts
  resources :stores
  resources :payrolls
  resources :employees
  resources :administrators, except: [:destroy]
  resources :payments, only: %i[new create]

  devise_for :users

  devise_scope :user do
    get 'users/table', to: 'users/registrations#table', as: 'user_table'
  end

  resources :products do
    post 'comprar', on: :member
    collection do
      get 'search'
      get 'table'
    end
  end

  resources :purchases do
    patch 'close', on: :member
    collection do
      get 'user_last_purchase'
    end
  end

  resources :departments do
    collection do
      get 'table'
    end
  end

  resources :categories do
    collection do
      get 'table'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  delete '/item_purchases/:id', to: 'item_purchases#destroy', as: 'item_purchase'

  resources :item_purchases do
    member do
      post 'growth'
      post 'reduction'
    end
  end

  root 'products#index'
end

app/controllers/purchases_controller.rb
# frozen_string_literal: true

class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]

  # GET /purchases or /purchases.json
  def index
    @purchases = current_user.purchases
  end

  # GET /purchases/1 or /purchases/1.json
  def show; end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit; end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    if @purchase.save
      render json: @purchase, status: :created, location: @purchase
    else
      render json: @purchase.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /purchases/1
  def update
    if @purchase.update(purchase_params)
      render json: @purchase
    else
      render json: @purchase.errors, status: :unprocessable_entity
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy!
  end

  def user_last_purchase
    @last_purchase = current_user.purchases.where(closed: false).order(created_at: :desc).first
    redirect_to @last_purchase
  end

  def close
    @purchase = Purchase.find(params[:id])
    @purchase.update(closed: true)
    current_user.purchases.create(
      closed: false,
      paid: false,
      price: 0.00,
      packageSize: 0.0,
      receive: false
    )
    redirect_to new_payment_path(purchase_id: @purchase.id, price: @purchase.price)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:user_id, :price, :paid, :packageSize, :receive, :closed)
  end
end

app/helpers/purchases_helper.rb
# frozen_string_literal: true

module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :paid, style: "display: block" %>
    <%= form.check_box :paid %>
  </div>

    <div>
    <%= form.label :closed, style: "display: block" %>
    <%= form.check_box :closed %>
  </div>

  <div>
    <%= form.label :packageSize, style: "display: block" %>
    <%= form.text_field :packageSize %>
  </div>

  <div>
    <%= form.label :receive, style: "display: block" %>
    <%= form.check_box :receive %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>">
  <p>
    <strong>User:</strong>
    <%= purchase.user_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= purchase.price %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= purchase.paid %>
  </p>

    <p>
    <strong>Closed:</strong>
    <%= purchase.closed %>
  </p>

  <p>
    <strong>Packagesize:</strong>
    <%= purchase.packageSize %>
  </p>

  <p>
    <strong>Receive:</strong>
    <%= purchase.receive %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<% @purchases.where(closed: true).each do |purchase| %>
  <%= link_to purchase, class: "text-dark link-underline-light" do %>
    <div class="d-flex py-3 my-5 border rounded container">
      <div class="col-5 px-5 mt-2">
        <small class="mt-2">
          <% names = purchase.item_purchases.map { |item_purchase| item_purchase.product.name } %>
          <% names.each_with_index do |name, index| %>
            <%= truncate(name, length: 40, separator: ' ') %>
            <% unless index == names.size - 1 %>
              <% unless name.length < 40 %>
                <%= ', ' unless index == names.size - 2 %>
              <% else %>
                <%= ', ' unless index == names.size - 1 %>
              <% end %>
            <% end %>
          <% end %>
        </small>
      </div>
      <div class="col-3 mt-3 row">
        <h6 class="mb-0"><%= number_to_currency(purchase.price) %></h6>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <% purchase.item_purchases.each do |item_purchase| %>
          <%= image_tag item_purchase.product.photo1, class: "bd-placeholder-img w-auto mr-2", width: "64", height: "64", preserveAspectRatio: "xMidYMid slice", alt: item_purchase.product.name %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-center">
  <div class="containerhistory mt-5 mb-3">
    <% @purchase.item_purchases.each do |item_purchase| %>
      <div class="d-flex py-3 my-1 border rounded">
        <div class="col-5 px-5 mt-2">
          <h6 class="mb-0"><%= item_purchase.product.name %></h6>
          <small class="text-body-secondary"><%= number_to_currency(item_purchase.value) %></small>
        </div>
        <div class="col-3 mt-3 row">
          <div class="input-group-prepend col-2 mx-3">
            <% if @purchase.price != 0 and @purchase.closed != true %>
              <%= button_to '-', reduction_item_purchase_path(item_purchase), method: :post, class: 'btn btn-outline-secondary' %>
            <% end %>
          </div>
          <small class="text-body-secondary col-1 mt-2"><%= item_purchase.quantity %></small>
          <div class="input-group-append col-2">
            <% if @purchase.price != 0 and @purchase.closed != true %>
              <%= button_to '+', growth_item_purchase_path(item_purchase), method: :post, class: 'btn btn-outline-secondary' %>
            <% end %>
          </div>
        </div>
        <div class="col-2">
          <%= image_tag item_purchase.product.photo1, class: "bd-placeholder-img w-auto mr-2", width: "64", height: "64", preserveAspectRatio: "xMidYMid slice", alt: item_purchase.product.name %>
        </div>
        <div class="col-1 mt-3">
          <% if @purchase.price != 0 and @purchase.closed != true %>
            <%= button_to 'Apagar', item_purchase_path(item_purchase), method: :delete, class: 'btn btn-danger', data: { confirm: 'Tem certeza que deseja apagar este item?' } %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container d-flex flex-column">
  <div class="row justify-content-center">
    <div class="col-4">
      <% if @purchase.price != 0 and @purchase.closed != true %>
        <%= form_with(model: @purchase, url: close_purchase_path(@purchase), method: :patch) do |form| %>
          <%= form.button type: :submit, class: "btn btn-primary", onclick: "return confirm('Tem certeza que deseja fechar esta compra?')" do %>
            Fechar Compra
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-5 text-center mt-2 mt-auto">
      <h4>Total: <%= number_to_currency(@purchase.price) %></h4>
    </div>
  </div>
</div>