config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :abouts
  resources :stores
  resources :payrolls
  resources :employees
  resources :administrators, except: [:destroy]
  resources :payments, only: %i[new create]

  devise_for :users

  devise_scope :user do
    get 'users/table', to: 'users/registrations#table', as: 'user_table'
  end

  resources :products do
    post 'comprar', on: :member
    collection do
      get 'search'
      get 'table'
    end
  end

  resources :purchases do
    patch 'close', on: :member
    collection do
      get 'user_last_purchase'
    end
  end

  resources :departments do
    collection do
      get 'table'
    end
  end

  resources :categories do
    collection do
      get 'table'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  delete '/item_purchases/:id', to: 'item_purchases#destroy', as: 'item_purchase'

  resources :item_purchases do
    member do
      post 'growth'
      post 'reduction'
    end
  end

  root 'products#index'
end

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center mt-3 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <%= image_tag(@current_store.logo) if @current_store.logo.attached? %>
      <span class="mb-md-0 text-body-secondary mx-3 mt-4">© <%= @current_store.created_at.year %> Company, Inc</span>
    </div>

    <ul class="nav justify-content-center border-bottom pb-3 my-3">
      <li class="nav-item mt-3 ms-3"><%= link_to "Página Principal", products_path, class: "nav-link px-2 text-body-secondary" %></li>
      <li class="nav-item mt-3 ms-3"><%= link_to "Sobre", abouts_path, class: "nav-link px-2 text-body-secondary" %></li>
    </ul>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <% if @current_store.facebook? %>
        <li class="ms-3">
          <a href="<%= @current_store.facebook %>" target="_blank">
            <i class="bi bi-facebook" style="font-size: 2rem; color: lightgray;"></i>
          </a>
        </li>
      <% end %>
      <% if @current_store.instagram? %>
        <li class="ms-3">
          <a href="<%= @current_store.instagram %>" target="_blank">
            <i class="bi bi-instagram" style="font-size: 2rem; color: lightgray;"></i>
          </a>
        </li>
      <% end %>
      <% if @current_store.twitter? %>
        <li class="ms-3">
          <a href="<%= @current_store.twitter %>" target="_blank">
            <i class="bi bi-twitter" style="font-size: 2rem; color: lightgray;"></i>
          </a>
        </li>
      <% end %>
    </ul>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="col bg-secondary ">
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between pt-4 mb-2">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <%= image_tag(@current_store.logo) if @current_store.logo.attached? %>
        </svg>
      </a>

      <div class="col-md-5">
        <%= form_tag search_products_path, method: :get do %>
          <div class="input-group my-1">
            <%= text_field_tag :keyword, params[:keyword], class: "form-control border border-primary", placeholder: "Buscar produtos por nome, categoria ou departamento" %>
            <button type="submit" class="btn btn-outline-primary bg-light" type="button">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
              </svg>
            </button>
          </div>
        <% end %>
      </div>

      <div class="col-md-3 text-end">
  <% if user_signed_in? %>
    <div class="dropdown">
      <button class="btn btn-light text-primary link-underline-light" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        <i class="bi bi-card-checklist"></i> Menu
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to user_last_purchase_purchases_path(current_user), class: "dropdown-item ml-2 text-primary" do %>
            <i class="bi bi-cart-check "></i>Carrinho
          <% end %>
        </li>
        <li>
          <%= link_to purchases_path, class: "dropdown-item ml-2 text-primary" do %>
            <i class="bi bi-card-checklist "></i> Histórico
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item ml-2 text-primary" do %>
            <i class="bi bi-door-closed"></i> Sair
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="dropdown">
      <button class="btn btn-light text-primary link-underline-light" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        <i class="bi bi-list-ul"></i> Menu
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to new_user_session_path(), class: "dropdown-item ml-2 text-primary" do %>
            <i class="bi bi-door-open-fill"></i> Login
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path(), class: "dropdown-item ml-2 text-primary" do %>
            <i class="bi bi-card-checklist "></i> Cadastro
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
</div>

  <div class="row bg-secondary border-top mt-2" style="padding-left: 5%; padding-right: 5%; width:99.7vw">
    <div class="dropdown col">
      <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-color:transparent;">
        Todas os Departamentos
      </button>
      <ul class="dropdown-menu multi-column">
        <% @departmentsAll.each do |department| %>
            <li><%= link_to department.name, department_path(department), class: "dropdown-item ml-2" %></li>
          <% department.categories.each do |category| %>
            <li><%= link_to category.name, category_path(category), class: "dropdown-item ml-2 text-black-50" %></li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <% [@top_departments.first, @top_departments.second, @top_departments.third, @top_departments.fourth].each do |top_department| %>
      <div class="col">
        <div class="dropdown">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-color:transparent;">
            <%= t("department_names.#{top_department.name}", default: top_department.name) %>
          </button>
          <ul class="dropdown-menu">
            <% top_department.categories.each do |category| %>
              <li><%= link_to category.name, category_path(category), class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</nav>