config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :abouts
  resources :stores
  resources :payrolls
  resources :employees
  resources :administrators, except: [:destroy]
  resources :payments, only: %i[new create]

  devise_for :users

  devise_scope :user do
    get 'users/table', to: 'users/registrations#table', as: 'user_table'
  end

  resources :products do
    post 'comprar', on: :member
    collection do
      get 'search'
      get 'table'
    end
  end

  resources :purchases do
    patch 'close', on: :member
    collection do
      get 'user_last_purchase'
    end
  end

  resources :departments do
    collection do
      get 'table'
    end
  end

  resources :categories do
    collection do
      get 'table'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  delete '/item_purchases/:id', to: 'item_purchases#destroy', as: 'item_purchase'

  resources :item_purchases do
    member do
      post 'growth'
      post 'reduction'
    end
  end

  root 'products#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_many :item_purchases

  has_one_attached :photo1
  has_one_attached :photo2
  has_one_attached :photo3

  after_create :increment_category_quantity
  after_destroy :decrement_category_quantity

  validates :name, presence: { message: 'Não pode ser vazio' }
  validates :category, presence: { message: 'Deve ser associado a uma categoria' }
  validates :weight, :width, :length, :valueBuy, :valueSell, :depth, :quantity,
            numericality: { greater_than: 0, message: 'Deve ser maior que zero' }
  validates :valueSell, numericality: { greater_than: :valueBuy, message: 'deve ser maior do que o valor de compra' }

  def increment_category_quantity
    category.increment!(:quantity)
  end

  def decrement_category_quantity
    category.decrement!(:quantity)
  end

  def self.search(keyword)
    where('products.name LIKE ?', "%#{keyword}%")
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = if params[:keyword].present?
                  Product.search(params[:keyword]).order(quantity: :desc).page(params[:page]).per(15)
                else
                  Product.order(quantity: :desc).page(params[:page]).per(15)
                end
  end

  def search
    @products = Product.search(params[:keyword]).order(quantity: :desc).page(params[:page]).per(15)
    render :index
  end

  def table
    @products = Product.order(valueSell: :desc).page(params[:page]).per(8)
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @product.quantity.zero?
      @product.destroy
      flash[:notice] = 'product was successfully destroyed.'
    else
      flash[:alert] = 'Cannot delete product with quantity greater than zero.'
    end
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def comprar
    if current_user
      @product = Product.find(params[:id])
      purchase = current_user.purchases.last || current_user.purchases.create
      purchase.item_purchases.create(product: @product, quantity: 1)
      redirect_to purchase_path(purchase), notice: 'Produto adicionado ao carrinho com sucesso!'
    else
      redirect_to new_user_session_path, alert: 'Por favor, faça login para continuar.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find_by(id: params[:id])
    return if @product

    flash[:alert] = 'Product not found.'
    redirect_to products_url
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :weight, :width, :length, :valueSell, :valueBuy, :depth, :quantity,
                                    :description, :category_id, :photo1, :photo2, :photo3)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/edit.html.erb
<h1>New product</h1>

<div class="container mt-5">
  <div style="margin: 0 15%;">
    <%= form_with(model: @product) do |form| %>
      <% if @product.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mt-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control mt-3" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :weight %>
        <%= form.text_field :weight, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :width %>
        <%= form.text_field :width, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :length %>
        <%= form.text_field :length, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :valueSell %>
        <%= form.text_field :valueSell, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :valueBuy %>
        <%= form.text_field :valueBuy, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :depth %>
        <%= form.text_field :depth, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo1 %>
        <%= form.file_field :photo1, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo2 %>
        <%= form.file_field :photo2, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo3 %>
        <%= form.file_field :photo3, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :category_id %>
        <%= form.collection_select(:category_id, Category.all, :id, :name, { prompt: true }, { class: 'form-control select2' }) %>
      </div>

      <div class="form-group my-5">
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3 mt-5" style="margin-left: 10%; margin-right: 10%;">
  <% @products.each do |product| %>
    <div class="col">
      <div class="card shadow-sm mb-3">
          <%= link_to product, style: "text-decoration: none; color: inherit;" do %>
          <% if product.photo1.attached? %>
            <%= image_tag product.photo1, class: "img-fluid", style: "object-fit: cover; width: 100%; height: 225px;" %>
          <% else %>
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="50%" y="50%" fill="#eceeef" dy=".3em" text-anchor="middle" alignment-baseline="middle">Sem foto</text>
            </svg>
          <% end %>
          <div class="card-body">
            <h6 class="mb-2"><%= product.name %></h6>
            <p class="mb-1"><small><%= product.description %></small></p>
            <p class="mb-1"><small><strong>R$<%= product.valueSell %></strong></small></p>
            <div class="d-flex justify-content-between align-items-center">
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center align-items-center custom-pagination pt-5">
    <%= paginate @products, theme: 'bootstrap-5',
                   pagination_class: "pagination-sm flex-wrap justify-content-center",
                   nav_class: "d-inline-block" %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<div class="container mt-5">
  <div style="margin: 0 15%;">
    <%= form_with(model: @product) do |form| %>
      <% if @product.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mt-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control mt-3" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :weight %>
        <%= form.text_field :weight, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :width %>
        <%= form.text_field :width, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :length %>
        <%= form.text_field :length, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :valueSell %>
        <%= form.text_field :valueSell, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :valueBuy %>
        <%= form.text_field :valueBuy, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :depth %>
        <%= form.text_field :depth, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo1 %>
        <%= form.file_field :photo1, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo2 %>
        <%= form.file_field :photo2, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :photo3 %>
        <%= form.file_field :photo3, class: "form-control" %>
      </div>

      <div class="form-group my-5">
        <%= form.label :category_id %>
        <%= form.collection_select(:category_id, Category.all, :id, :name, { prompt: true }, { class: 'form-control select2' }) %>
      </div>

      <div class="form-group my-5">
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div class="row p-4 rounded-2 mb-5" style="margin-top: 5%; margin-left: 20%; margin-right: 20%; background-color: lightgray;">
  <div class="col-md-6">
    <div id="productCarousel" class="carousel slide " data-bs-ride="carousel" style="width: 18vw; height: 7vw;">
      <div class="carousel-inner rounded-2">
        <% if @product.photo1.attached? %>
          <div class="carousel-item active">
            <%= image_tag @product.photo1, class: "d-block w-100", style: "aspect-ratio: 3/4;", alt: "Main Photo" %>
          </div>
        <% end %>

        <% if @product.photo2.attached? %>
          <div class="carousel-item">
            <%= image_tag @product.photo2, class: "d-block w-100", style: "aspect-ratio: 3/4;", alt: "Photo 2" %>
          </div>
        <% end %>

        <% if @product.photo3.attached? %>
          <div class="carousel-item">
            <%= image_tag @product.photo3, class: "d-block w-100", style: "aspect-ratio: 3/4;", alt: "Photo 3" %>
          </div>
        <% end %>
      </div>
      <div style="margin-top: 15%; margin-left: 20%; margin-right: 20%;">
        <button class="carousel-control-prev" type="button" data-bs-target="#productCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#productCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

    </div>
  </div>

  <div class="col-md-6 ">
    <h3 class="text-dark mt-3 mr-5">
      <%= @product.name %>
    </h3>
    <p>No estoque: <%= @product.quantity %></p>

    <h1 class="text-center" style="margin-top:48px; margin-bottom:24px"><strong>R$ <%= @product.valueSell %></strong></h1>

<div class="text-center mb-2">
  <%= form_tag comprar_product_path(@product), method: :post, class: "mb-4" do %>
    <%= button_tag type: "submit", class: "btn btn-secondary my-4 px-5" do %>
      <h4>Comprar</h4>
    <% end %>
  <% end %>
</div>

      <p class="pt-4">dimensões<%= @product.depth %>x<%= @product.width %>x<%= @product.length %></p>
      <p><%= @product.description %></p>

  </div>

</div class="pb-5">

<script>
document.addEventListener("DOMContentLoaded", function() {
  const productCarousel = new bootstrap.Carousel(document.getElementById("productCarousel"));

  // Atualizar a foto principal ao clicar em um slide do carrossel
  productCarousel._element.addEventListener("slid.bs.carousel", function(event) {
    const activePhoto = event.relatedTarget.querySelector("img");
    const mainPhoto = document.getElementById("main-photo");
  });
});
</script>

app/views/products/table.html.erb
<p style="color: green; text-align: center;"><%= notice %></p>
<p style="color: red; text-align: center;"><%= alert %></p>
<h1 class="text-center">Produtos</h1>
<div style="margin-left: 10%; margin-right: 10%;">

  <table class="table table-striped align-middle text-center border border-primary rounded p-3 my-5">
    <thead>
      <tr>
        <th scope="col" class="text-start text-center align-middle pe-4">ID</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Nome</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Peso</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Largura</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Comprimento</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Valor de Venda</th>
        <th scope="col" class="text-start text-center align-middle pe-4">Quantidade</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row" class="text-start text-center align-middle pe-4"><%= product.id %></th>
          <td class="text-start text-center align-middle pe-4"><%= product.name %></td>
          <td><%= product.weight %></td>
          <td><%= product.width %></td>
          <td><%= product.length %></td>
          <td><%= product.valueSell %></td>
          <td><%= product.quantity %></td>
          <td class="text-end align-middle">
            <div class="d-flex justify-content-end">
              <%= link_to "Ver item", product, class: "btn btn-primary me-2" %>
              <%= link_to "Editar item", edit_product_path(product), class: "btn btn-dark me-2" %>
              <%= button_to "Deletar item", product, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center align-items-center custom-pagination">
    <%= paginate @products, outer_window: 2, inner_window: 2 %>
  </div>

  <%= link_to "Novo produto", new_product_path, class: "btn btn-primary btn-block mt-5" %>
</div>